# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here            
      - image: circleci/openjdk:8u181-jdk-node-browsers
      - image: circleci/android:api-25-alpha
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    environment:      
      ANDROID_HOME: /usr/local/android-sdk-linux
      JVM_OPTS: -Xmx3200m
      

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: bash ./.circleci/download.sh
      - run: ls -lrt /home/circleci/repo/      
      - run: npm --version
      - run: npm install six
      - run: npm i npm@latest
      - run: npm --version
      - run: node -v
      - run: npm install 
      - run: npm install nativescript-cloud      
      - run: sudo npm install nativescript -g --unsafe-perm            
      - run: echo yes | tns setup
      - run: echo yes | tns cloud setup
      - run: echo yes | tns doctor
      - run: echo -n $'\031' | tns build android --env.snapshot --env.uglify --release --key-store-path $KEYSTORE --key-store-password $KEYSTORE_PASSWORD --key-store-alias sasquiz --key-store-alias-password $KEYSTORE_PASSWORD --copy-to base.apk
